---
title: "Assignment 1"
---

# Assignment 1

```{r}
1 + 1
```

My first assignment has two parts.

## (a)

## (b)

```{r}
library(dslabs)
data("polls_us_election_2016")
```

```{r}
my_first <- "Ece"
my_birth_year <- 2002 
```

```{r}
k <- (nchar(my_first) + my_birth_year) %% 15 + 8
```

```{r}
if (k %% 2 == 0) {
  print(head(polls_us_election_2016, k))
} else {
  print(tail(polls_us_election_2016, k))
}
```

```{r}
total_na <- sum(is.na(polls_us_election_2016))
cat("Total number of NA's in the dataset:", total_na, "\n\n")
```

```{r}
na_per_col <- colSums(is.na(polls_us_election_2016))
print("First 8 columns that contains the most NA's:")
head(sort(na_per_col, decreasing = TRUE), 8)
```

```{r}
new_data <- polls_us_election_2016
```

```{r}
for(col in names(new_data)){
  if(is.numeric(new_data[[col]])){
    # Sayısal sütunlar için: Doğum yılı + k
    new_data[[col]][is.na(new_data[[col]])] <- my_birth_year + k
  } else if(is.character(new_data[[col]]) | is.factor(new_data[[col]])){
    # Karakter/Faktör sütunları için: İsim + k
    new_data[[col]][is.na(new_data[[col]])] <- paste0(my_first, "", k)
  }
}
```

```{r}
cat("\nYeni veri setinin k satırlık görünümü:\n")
if (k %% 2 == 0) {
  print(head(new_data, k))
} else {
  print(tail(new_data, k))
}
```

```{r}
kalan_na <- sum(is.na(new_data))
cat("\nYeni veri setindeki toplam NA sayısı:", kalan_na, "\n")
```

```{r}
cat("Veri setinde hiç NA kaldı mı? ")
anyNA(new_data)
```
